# Generated by Django 5.0.7 on 2024-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation", old_name="items", new_name="item",
        ),
    ]
