# Generated by Django 5.0.7 on 2024-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_rename_items_conversation_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="Conversation",
            new_name="conversation",
        ),
    ]
