# Generated by Django 5.0.7 on 2024-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0003_rename_conversation_conversationmessage_conversation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation", options={"ordering": ("-modified_at",)},
        ),
        migrations.RenameField(
            model_name="conversation", old_name="modefied_at", new_name="modified_at",
        ),
    ]
